### ISSUE TITLE
Favicon breaks on any nested pages

### ISSUE THREAD

**Issue by nicksuch** [ainc/ainc-2018#145]
Works on homepage and any top-level pages, but 404s on pages like `/learn/youth` and /bootcamp/apply` 

Seems to be a relative URL issue here in [_includes/head.html](https://github.com/ainc/ainc-2018/blob/7a1e27cc38adfcddffb3186009c7568556346354/_includes/head.html)

**Comment by raney24** [comment]
@nicksuch Thanks for opening this! Should be fixed now.
