### ISSUE TITLE
Main URL for 5 Across event has .html ending

### ISSUE THREAD

**Issue by nicksuch** [ainc/ainc-2018#147]
Current URL for 5 Across event (when redirected from 5across.org) is https://www.awesomeinc.org/recurring_events/5across.html 

Instead, it should be https://www.awesomeinc.org/recurring_events/5across

It looks like the permalink setting for the Recurring Event collection is commented out in the Config: https://github.com/ainc/ainc-2018/blob/master/_config.yml

**Comment by raney24** [comment]
Should be fixed now. The path is now awesomeinc.org/events/5across.
